/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountOverviewCard: typeof import('./features/account/components/AccountOverviewCard.vue')['default']
    AppButton: typeof import('@repo/ui')['AppButton']
    AppConfigProvider: typeof import('@repo/ui')['AppConfigProvider']
    AppNavbar: typeof import('@repo/ui')['AppNavbar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NResult: typeof import('naive-ui')['NResult']
    ProfileForm: typeof import('./features/profile/components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
